steps:
  # Clone submodules (pxt-common-packages and pxt)
  - name: 'gcr.io/cloud-builders/git'
    args: ['submodule', 'update', '--init', '--recursive']
  
  # Run the prune script to remove non-ESP32-S2 boards
  - name: 'ubuntu'
    script: |
      chmod +x scripts/prune-for-esp32s2.sh
      ./scripts/prune-for-esp32s2.sh
  
  # Install dependencies and build
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['install']
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['run', 'build']
  
  # Deploy to Firebase
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'deploy']
  
options:
  machineType: 'E2_HIGHCPU_8'
  env:
    - 'FIREBASE_PROJECT=springbot-co-za'
