# Cloud Build config – no substitutions, all logic in scripts.
# Logs to Cloud Logging only (satisfies the service account/logging rule).
steps:
  # 0) Initialize submodules (pxt-common-packages and pxt)
  - id: submodule-init
    name: gcr.io/cloud-builders/git
    args: ['submodule', 'update', '--init', '--recursive']

  # 1) Install build deps and npm packages (inside Node image)
  - id: npm-install
    name: node:20
    entrypoint: bash
    args:
      - -lc
      - |
        set -euo pipefail
        bash scripts/build.sh install

  # 2) Prune to minimal esp32-s2 target + build static package
  - id: build
    name: node:20
    entrypoint: bash
    args:
      - -lc
      - |
        set -euo pipefail
        bash scripts/build.sh build

# Keep logs in Cloud Logging (option a); no logs bucket, no substitutions used.
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: E2_HIGHCPU_8
