options:
  logging: CLOUD_LOGGING_ONLY
  machineType: E2_HIGHCPU_8

substitutions:
  _REPO_PXT: "https://github.com/domino4com/pxt.git"
  _REPO_PKGS: "https://github.com/domino4com/pxt-common-packages.git"
  _FIREBASE_PROJECT: "springbot-co-za"

steps:
# 0) Clone pxt
- name: gcr.io/cloud-builders/git
  id: "Clone pxt"
  entrypoint: bash
  args:
    - -lc
    - |
      git clone ${_REPO_PXT} pxt

# 1) Clone pxt-common-packages
- name: gcr.io/cloud-builders/git
  id: "Clone pxt-common-packages"
  entrypoint: bash
  args:
    - -lc
    - |
      git clone ${_REPO_PKGS} pxt-common-packages

# 2) Build pxt core
- name: node:18
  id: "Build pxt core"
  entrypoint: bash
  args:
    - -lc
    - |
      set -euxo pipefail
      cd pxt
      rm -f package-lock.json
      npm ci || npm install
      npm run build

# 3) Install pxt-common-packages deps
- name: node:18
  id: "Install pxt-common-packages"
  entrypoint: bash
  args:
    - -lc
    - |
      set -euxo pipefail
      cd pxt-common-packages
      rm -f package-lock.json
      npm ci || npm install

# 4) Install target deps (root)
- name: node:18
  id: "Install target deps (pxt-maker)"
  entrypoint: bash
  args:
    - -lc
    - |
      set -euxo pipefail
      rm -f package-lock.json
      npm ci || npm install

# 5) Prune for ESP32-S2 (springbot) and link
- name: node:18
  id: "Prune for ESP32-S2 (springbot)"
  entrypoint: bash
  args:
    - -lc
    - |
      set -euxo pipefail
      chmod +x scripts/prune-for-esp32s2.sh
      ./scripts/prune-for-esp32s2.sh
      npm config set fund false
      npm config set audit false
      npx --yes pxt@0.5.1 link ./pxt
      npx --yes pxt@0.5.1 link ./pxt-common-packages

# 6) Re-install after linking
- name: node:18
  id: "Link & build target"
  entrypoint: bash
  args:
    - -lc
    - |
      set -euxo pipefail
      rm -rf node_modules package-lock.json
      npm ci || npm install

# 7) Static pkg + Firebase deploy (no $PUB in YAML)
- name: node:18
  id: "Static pkg + Firebase deploy"
  entrypoint: bash
  args:
    - -lc
    - |
      set -euxo pipefail

      # Build static package
      npx --yes pxt@0.5.1 staticpkg --noMini

      # Detect output dir
      PUB=""
      for d in docs built/packaged pxt/built/web built/web; do
        if [ -d "$d" ]; then PUB="$d"; break; fi
      done
      if [ -z "$PUB" ]; then
        echo "Could not find staticpkg output."
        find . -maxdepth 3 -type d | sed 's|^\./||'
        exit 1
      fi
      echo "Using public dir: ${PUB}"

      # Write firebase config with placeholder, then replace via sed
      cat > firebase.json <<'EOF'
      {
        "hosting": {
          "public": "__PUBLIC_DIR__",
          "ignore": ["firebase.json", "**/.*", "**/node_modules/**"]
        }
      }
      EOF
      sed -i "s|__PUBLIC_DIR__|${PUB}|g" firebase.json

      cat > .firebaserc <<EOF
      {
        "projects": {
          "default": "${_FIREBASE_PROJECT}"
        }
      }
      EOF

      npm i -g firebase-tools
      firebase deploy --only hosting --project "${_FIREBASE_PROJECT}" --non-interactive

artifacts:
  objects:
    location: gs://$PROJECT_ID-build-artifacts/staticpkg/
    paths:
      - "docs/**"
      - "built/packaged/**"
      - "pxt/built/web/**"
      - "built/web/**"
