# Cloud Build config — no substitutions; all logic in scripts.
steps:
  # 0) Init submodules
  - id: submodule-init
    name: gcr.io/cloud-builders/git
    args: ['submodule', 'update', '--init', '--recursive']

  # 1) Install build deps + npm
  - id: npm-install
    name: node:20
    entrypoint: bash
    args:
      - -lc
      - |
        set -euo pipefail
        bash scripts/build.sh install

  # 2) Prune to only the springbot board and build static package
  - id: build
    name: node:20
    entrypoint: bash
    args:
      - -lc
      - |
        set -euo pipefail
        bash scripts/build.sh build

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: E2_HIGHCPU_8
