# cloudbuild.yaml — build pxt-maker (repo root) and deploy to Firebase Hosting
# Values you gave:
# _FIREBASE_PROJECT: springbot-co-za
# _FIREBASE_SITE: springbot
# _GITHUB_ORG: domino4com

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _FIREBASE_PROJECT: springbot-co-za
  _FIREBASE_SITE: springbot
  _GITHUB_ORG: domino4com

steps:
# Clone PXT core + common packages into /workspace
- name: 'gcr.io/cloud-builders/git'
  args: ['clone', 'https://github.com/${_GITHUB_ORG}/pxt', 'pxt']

- name: 'gcr.io/cloud-builders/git'
  args: ['clone', 'https://github.com/${_GITHUB_ORG}/pxt-common-packages', 'pxt-common-packages']

# Use Node 18 for all npm/pxt work; NO global installs
# Build PXT core
- name: 'node:18'
  dir: 'pxt'
  entrypoint: 'bash'
  args:
    - -lc
    - |
      set -euo pipefail
      npm ci
      npm run build

# Install common packages
- name: 'node:18'
  dir: 'pxt-common-packages'
  entrypoint: 'bash'
  args: ['-lc', 'set -euo pipefail; npm ci' ]

# Install deps for your pxt-maker fork (repo root)
- name: 'node:18'
  entrypoint: 'bash'
  args: ['-lc', 'set -euo pipefail; npm ci' ]

# Link local pxt + common packages into this target (via npx)
- name: 'node:18'
  entrypoint: 'bash'
  args:
    - -lc
    - |
      set -euo pipefail
      npx pxt link ./pxt
      npx pxt link ./pxt-common-packages

# Build static package to ./site (via npx). Also write minimal firebase.json
- name: 'node:18'
  entrypoint: 'bash'
  args:
    - -lc
    - |
      set -euo pipefail
      npx pxt staticpkg --githubpages --output ./site
      cat > firebase.json <<'JSON'
      { "hosting": { "public": "site", "ignore": ["firebase.json", "**/.*", "**/node_modules/**"] } }
      JSON

# Ensure Hosting site exists; then deploy using FIREBASE_TOKEN from Secret Manager
- name: 'node:18'
  entrypoint: 'bash'
  secretEnv: ['FIREBASE_TOKEN']
  args:
    - -lc
    - |
      set -euo pipefail
      npx firebase-tools hosting:sites:create "${_FIREBASE_SITE}" --project "${_FIREBASE_PROJECT}" || true
      npx firebase-tools deploy --non-interactive \
        --only hosting \
        --project "${_FIREBASE_PROJECT}" \
        --site "${_FIREBASE_SITE}"

availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/FIREBASE_TOKEN/versions/latest
    env: 'FIREBASE_TOKEN'
