# cloudbuild.yaml — springbot / ESP32-S2 focused

options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # 0) Clone pxt (core)
  - name: gcr.io/cloud-builders/git
    id: Clone pxt
    entrypoint: bash
    args:
      - -lc
      - |
        set -euxo pipefail
        git clone https://github.com/domino4com/pxt.git

  # 1) Clone pxt-common-packages
  - name: gcr.io/cloud-builders/git
    id: Clone pxt-common-packages
    entrypoint: bash
    args:
      - -lc
      - |
        set -euxo pipefail
        git clone https://github.com/domino4com/pxt-common-packages.git

  # 2) Build pxt core
  - name: node:18
    id: Build pxt core
    entrypoint: bash
    args:
      - -lc
      - |
        set -euxo pipefail
        node -v
        npm -v
        cd pxt
        rm -f package-lock.json || true
        npm install
        npm run build

  # 3) Install deps for pxt-common-packages
  - name: node:18
    id: Install pxt-common-packages
    entrypoint: bash
    args:
      - -lc
      - |
        set -euxo pipefail
        cd pxt-common-packages
        rm -f package-lock.json || true
        npm install

  # 4) Install deps for the target repo (this repo)
  - name: node:18
    id: Install target deps (pxt-maker)
    entrypoint: bash
    args:
      - -lc
      - |
        set -euxo pipefail
        node -v
        npm -v
        rm -f package-lock.json || true
        npm install

  # 5) Prune non-ESP MCUs & connectivity libs
  - name: node:18
    id: Prune for ESP32-S2 (springbot)
    entrypoint: bash
    args:
      - -lc
      - |
        set -euxo pipefail
        test -f scripts/prune-for-esp32s2.sh
        chmod +x scripts/prune-for-esp32s2.sh
        ./scripts/prune-for-esp32s2.sh

  # 6) Link local pxt + pxt-common-packages and build the target site
  - name: node:18
    id: Link & build target
    entrypoint: bash
    args:
      - -lc
      - |
        set -euxo pipefail

        # Safety: ensure no old installs block the symlink replacement
        rm -rf node_modules/pxt-core node_modules/pxt || true
        # (If anything nested got pulled in earlier, clear them too)
        rm -rf pxt/node_modules pxt-common-packages/node_modules || true

        # Make sure the target deps are still present after pruning
        rm -f package-lock.json || true
        npm install

        # Link to the local clones
        npx pxt link ./pxt
        npx pxt link ./pxt-common-packages

        # Build static site
        npx pxt clean
        npx pxt staticpkg

artifacts:
  objects:
    location: gs://$PROJECT_ID-cloudbuild-artifacts/springbot-site
    paths:
      - built/**
timeout: "3600s"
