steps:
  # Initialize and update submodules (pxt-common-packages and pxt)
  - name: 'gcr.io/cloud-builders/git'
    args: ['submodule', 'update', '--init', '--recursive']
    id: 'submodule-init'

  # Run the prune script to remove non-ESP32-S2 boards (like SAMD, NRF, RP2040)
  - name: 'ubuntu'
    script: |
      chmod +x scripts/prune-for-esp32s2.sh
      ./scripts/prune-for-esp32s2.sh
    id: 'prune-boards'

  # Install npm dependencies (with libudev-dev installed first)
  - name: 'node:20'
    entrypoint: bash
    args:
      - -lc
      - |
        set -euxo pipefail
        apt-get update
        DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends libudev-dev
        npm ci --unsafe-perm
    id: 'npm-install'

  # Build the project
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['run', 'build']
    id: 'npm-build'

  # Deploy to Firebase Hosting (requires FIREBASE_TOKEN)
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'deploy']
    env:
      - 'FIREBASE_TOKEN=${_FIREBASE_TOKEN}'
    id: 'firebase-deploy'

options:
  machineType: 'E2_HIGHCPU_8' # Use a higher-CPU machine for faster builds
  logging: CLOUD_LOGGING_ONLY
  env:
    - 'FIREBASE_PROJECT=springbot-co-za'

substitutions:
  _FIREBASE_TOKEN: 'your-firebase-token-here' # Set this in your trigger substitutions
