# ... your existing steps up to "Install deps (pxt-maker) + link" ...

# Prune to ESP32-S2 + allow-list; keep connectivity OFF for now
- name: 'node:18'
  id: Prune to ESP32-S2 only
  entrypoint: bash
  args:
    - -lc
    - |
      set -eux
      # ensure script exists (if not checked in yet, write it)
      mkdir -p scripts
      if [ ! -f scripts/prune-for-esp32s2.sh ]; then
        cat > scripts/prune-for-esp32s2.sh <<'BASH'
        #!/usr/bin/env bash
        set -euxo pipefail
        ENABLE_CONNECTIVITY="${ENABLE_CONNECTIVITY:-0}"
        pushd pxt-common-packages/libs
        find . -maxdepth 1 -type d \( -name '*---rp2040' -o -name '*---samd' -o -name '*---stm32' -o -name '*---nrf52' \) -print0 | xargs -0 rm -rf || true
        rm -rf core---rp2040 core---samd mixer---samd mixer---stm32 mixer---nrf52 || true
        if [ "${ENABLE_CONNECTIVITY}" != "1" ]; then
          rm -rf azureiot mqtt net net-game radio radio-broadcast lora || true
        else
          rm -rf radio radio-broadcast lora || true
        fi
        popd
        rm -rf node_modules/@types/node || true
        rm -rf pxt-common-packages/node_modules/@types/node || true
        rm -rf pxt/node_modules/@types/node || true
        find pxt-common-packages -path '*/settings/targetoverrides.ts' -print0 | xargs -0 rm -f || true
        BASH
        chmod +x scripts/prune-for-esp32s2.sh
      fi
      # RUN with connectivity OFF (fast/clean v1)
      ENABLE_CONNECTIVITY=0 ./scripts/prune-for-esp32s2.sh

# Build static site for Springbot target only
- name: 'node:18'
  id: Build static site (Springbot)
  entrypoint: bash
  args:
    - -lc
    - |
      set -eux
      cd pxt-maker
      export PXT_FORCE=1
      export PXT_NO_UPDATE=1
      npx pxt staticpkg --githubpages --output ../site
