steps:
  # Initialize and update submodules (pxt-common-packages and pxt)
  - name: 'gcr.io/cloud-builders/git'
    args: ['submodule', 'update', '--init', '--recursive']
    id: 'submodule-init'

  # Run the prune script to remove non-ESP32-S2 boards (like SAMD, NRF, RP2040)
  - name: 'ubuntu'
    script: |
      chmod +x scripts/prune-for-esp32s2.sh
      ./scripts/prune-for-esp32s2.sh
    id: 'prune-boards'

  # Install npm dependencies (install toolchain + udev, then npm install with C++17)
  - name: 'node:20'
    entrypoint: bash
    args:
      - -lc
      - |
        set -euxo pipefail
        apt-get update
        DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
          build-essential g++ libudev-dev
        # Force C++17 for native addons (Node 20 headers expect C++17)
        export CXXFLAGS="-std=gnu++17"
        npm install --unsafe-perm --no-audit --fund=false
    id: 'npm-install'

  # Build the project
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['run', 'build']
    id: 'npm-build'

  # Deploy to Firebase Hosting (requires FIREBASE_TOKEN)
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'deploy']
    env:
      - 'FIREBASE_TOKEN=${_FIREBASE_TOKEN}'
    id: 'firebase-deploy'

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
  env:
    - 'FIREBASE_PROJECT=springbot-co-za'

substitutions:
  _FIREBASE_TOKEN: 'your-firebase-token-here'
